### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by jtrees**
Copy-pasted from here: https://github.com/EnBWAG/netzlive.elsa/pull/2

I used a more recent versions for elixir and otp though.

### CODE REVIEW

**Review by DerTim1 — CHANGES_REQUESTED** [review]
@jtrees This repo is public. We shouldn't do project specific stuff here. Can we publish this to global and public hex.pm?

**Comment by jtrees** [comment]
> @jtrees This repo is public. We shouldn't do project specific stuff here.

Makes sense. I think we should rename the repo then though.

**Comment by kayiplar** [comment]
@jtrees Rename or make it private?

**Comment by jtrees** [comment]
> @jtrees Rename or make it private?

I'm no longer blocked by this and have no preference.

**Comment by DerTim1** [comment]
Private: -> publish to our own hex registry
Rename & Public: -> publish to hex.pm

Would prefer Rename & Public, but this is more work to do.

**Comment by jtrees** [comment]
Ich werde das Thema nicht weiter verfolgen.

**Pull request closed without merging**
